### ISSUE TITLE
Repeated use results in "Waiting for available socket"

### ISSUE THREAD

**Issue by negativx** [PactInteractive/image-downloader#10]
If I have been using the extension for a while, at some point it will stop working and Chrome displays "Waiting for available socket" in the status bar.  This state never really seems to clear until either I restart Chrome or reduce the number of open tabs down to single digits.

Eventually, it wil start to affect just clicking on links though there does not seem to be any kind of pattern.

**Comment by Karlheinzniebuhr** [comment]
same issue here, repeated use results in unresponsiveness of the extension, although I have no error output in the console..

**Comment by vdsabev** [comment]
I hope this issue has been resolved with the newer releases of the extension. If the issue persists, please leave a comment here or open a new issue. Thanks!
