### ISSUE TITLE
GUI broken since Chrome 116

### ISSUE THREAD

**Issue by makedir** [PactInteractive/image-downloader#114]
Since Chrome 116 the GUI of this addon is broken and cut off and you have to scroll to the right to see the entire page and access the download button on the right side.

Please fix this.

![image](https://github.com/PactInteractive/image-downloader/assets/6721083/3a5dddc0-37a9-4f89-9000-420465affadc)

**Comment by vdsabev** [comment]
Thanks for taking the time to file an issue!
It seems there have been changes to how flexbox / grid is rendered in Chromium 116: https://twitter.com/vdsabev/status/1701550722569908619
Taking a look now.

**Comment by vdsabev** [comment]
I've gotten to what I think is the minimum code necessary to reproduce this in an extension popup:
```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        background: red;
      }

      .parent {
        display: flex;
        flex-direction: column;
      }

      .child {
        width: 500px;
        height: 500px;
        background: blue;
      }
    </style>
  </head>

  <body>
    <div class="parent">
      <div class="child"></div>
    </div>
  </body>
</html>
```

Actual result:

![image](https://github.com/PactInteractive/image-downloader/assets/1333274/16fa0874-21a9-4886-be59-c391c3b239fe)

Expected result:

![image](https://github.com/PactInteractive/image-downloader/assets/1333274/0c2eddc3-12f3-4709-b818-7cc543ee071b)
