### ISSUE TITLE
Image downloader trying to rename a download not initiated through the extension

### ISSUE THREAD

**Issue by casualsailo** [PactInteractive/image-downloader#117]
## Setup
- Windows 10
- Chrome 120.0.6099.225
- Version 3.4.2

## Describe the bug or Screenshots
I installed an extension called FireShot which allows you to take screenshots of the entire webpage: https://chromewebstore.google.com/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg

Every time I save a screenshot using FireShot, Image Downloader throws an error message: This extension failed to name the download "" because another extension (Take Webpage Screenshots Entirely - FireShot) determined a different filename "FireShot_www.google.com_2024-01-29-11-15-11_Google.png".

Is there a reason why Image Downloader seems to be interacting with saving images that are not initiated through the extension?

![Image Downloader Error](https://github.com/PactInteractive/image-downloader/assets/16842318/d2e89da9-2f11-4296-9e1f-438c52b65db0)

**Comment by vdsabev** [comment]
Sadly, this is how the Chrome extension API works:
https://developer.chrome.com/docs/extensions/reference/api/downloads#event-onDeterminingFilename

> If more than one extension overrides the filename, then the last extension installed whose listener passes a `suggestion` object to `suggest` wins. In order to avoid confusion regarding which extension will win, users should not install extensions that may conflict.

**Comment by predictablefoley** [comment]
other extensions have been able to work around this issue, by installing and then removing their listeners after they are done handling their downloads. after experimenting with a handful of downloader extensions, it's seems that only Image Downloader trips up and generates this error, rendering the extension useless until all the other extensions are removed.
