### ISSUE TITLE
No longer working on FetLife

### ISSUE THREAD

**Issue by justjack143** [PactInteractive/image-downloader#28]
FetLife has been working on killing hotlinks and adding tokens. It stopped working a week or so ago with Image Downloader as a result.  Just a head's up.

**Comment by vdsabev** [comment]
I'm scared to open that website to test it myself 😅 But as of version 3.0.6 of the extension it handles referer security rules better. Please try again, and if the issue persists leave a comment here or open a new issue. Thank you!
