### ISSUE TITLE
Download tif images?

### ISSUE THREAD

**Issue by jamminjames** [PactInteractive/image-downloader#29]
When I use .tif in a wildcard download, it doesn't pick up any images. Does this downloader not work with tiffs? It finds the jpegs in the same folder. 

If not, will you consider adding the ability to download tiffs? It would be very helpful.

Thank you.

**Comment by vdsabev** [comment]
This has been fixed in version 3 of the extension - please try again! If the issue persists, leave a comment here or open a new issue. Thanks!
