### ISSUE TITLE
Download request disabled by server

### ISSUE THREAD

**Issue by HonorLee-cn** [PactInteractive/image-downloader#33]
Some websites forbidden download request,images only can be seen in normal web view.
Image-Downloader will not work (chrome stop download images)

Like this link:
http://a437.file-static.com/data/attachment/forum/threadcover/1801/11632374.jpg

Except right click and save as...that will work

**Comment by HonorLee-cn** [comment]
Tried again,it seems the request referrer issues.
Just visit this link is not allowed,but on the website and right click on the image to open in new tab works fine.

**Comment by vdsabev** [comment]
Referer issues have been fixed in version 3.0.6 of the extension - please try again. If the issue persists, leave a comment here or open a new issue. Thanks!

**Comment by yellowthing0** [comment]
this issue has recurred for me
