### ISSUE TITLE
Won't Recognize Images Due To New HTML Coding

### ISSUE THREAD

**Issue by greenguy89** [PactInteractive/image-downloader#38]
I use this every day & really love it, but the last few days I'm noticing some new HTML coding for image URLs that is causing the extension to not recognize some images.

Usually we'd see coding like this:
`<img src="https://www.blog.google/static/blog/images/google-200x200.7714256da16f.png" width="200" height="200" border="0">`

But the new coding I'm seeing looks like this:
`<img src="//www.blog.google/static/blog/images/google-200x200.7714256da16f.png" width="200" height="200" border="0">`

Notice that the https: is missing from the URL?  I have a feeling the extension is looking for the https: (or http:) and that's why it's not recognizing the images :(

I'd provide examples, but seeing as everything I use this for is NSFW, I wasn't sure if I was allowed to post any links.

Really hoping you can fix this!

**Comment by vdsabev** [comment]
Closing this issue as it hasn't had activity in a while. Hopefully it has been resolve in the latest version. If the issue persists, please leave a comment or open a new issue. Thanks!
