### ISSUE TITLE
REQ: Remember Last Used Folder

### ISSUE THREAD

**Issue by Zhurama** [PactInteractive/image-downloader#58]
I love this wonderful and necessary tool.. Please have it remember which folder you last used, as it is troublesome to have to keep selecting anything other than downloads, where pictyures don't belong anyway, just to stay organized..

TIA and Namaste...

Zhu.

**Comment by citricacid2** [comment]
Chrome doesn't let extensions choose a download folder that isn't a subdirectory. You can use symlinks to bypass this, however.

**Comment by team3star** [comment]
https://github.com/PactInteractive/image-downloader/issues/50#issuecomment-821915721

**Comment by vdsabev** [comment]
Hi @Zhurama and thank you for the kind words. You can change the default download directory in your browser settings. Chrome Extensions aren't allowed to save files anywhere outside the download directory you set. If you want to save the images to a subfolder, you can enter a path in the `Save to subfolder` text input. You can even save to folders multiple levels down, for example `parent-folder/child-folder/grandchild-folder`.

Let me know how it works out for you.
