### ISSUE TITLE
The file rename textbox

### ISSUE THREAD

**Issue by Don2021** [PactInteractive/image-downloader#59]
Excellent app, but the file name of the sequence rename is not as the sequence displayed online. E.g. the image showed at the bottom of web and this app (i.e. 52) is renamed to small numbers (i.e. 25).

**Comment by vdsabev** [comment]
Hi @Don2021, thanks for opening an issue. Could you provide a specific URL and steps to follow for reproducing this issue? Screenshots would work fine as well.

**Comment by Don2021** [comment]
Dear,

Thanks for your reply.

Here:  http://manganelos.com/jinrouki-winvurga-chapter-39









Sent from Mail for Windows 10

**Comment by vdsabev** [comment]
I think I understand now - on the URL you provided, I had to select `View: all images` from the dropdown. Then once I open the extension and download the files, the order of the renamed files doesn't match the order in which they're displayed in the popup.

I'll work on fixing this issue for the next release in the coming weeks.

**Comment by vdsabev** [comment]
Version 3.0.0 has now been published to the [Google Chrome Webstore](https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj)! Let me know how it works out. Thanks for your help!

**Comment by Don2021** [comment]
Since the development version, the sequence of the files saved in the expected order. I have upgraded to this version. It work well too and is easy to install..



Thanks.


Sent from Mail for Windows 10
