### ISSUE TITLE
Build Guide

### ISSUE THREAD

**Issue by shxnpie** [PactInteractive/image-downloader#60]
Looks like this project is active again but I haven't seen any updates on the Chrome Store yet, so I thought I'd build this extension myself but I was unable to find any build guide. So would you be so kinds to provide one in the Readme for users like me? Because that'd be really great!

**Comment by vdsabev** [comment]
Thank you for the suggestion, I'll make sure to add a more detailed build guide at some point.
For now you can try the following:
1. Run `npm install` in the root folder
2. Run `npm start`
3. Load the `build` folder as an unpacked extension.

    ![image](https://user-images.githubusercontent.com/1333274/114511971-3fac5d00-9c41-11eb-9463-91c281eed4b8.png)

    (detailed instructions here: https://developer.chrome.com/docs/extensions/mv3/getstarted/#manifest)

**Comment by vdsabev** [comment]
Added a build guide in README.md in #68 - also, for what it's worth the new version of the extension is out officially, so you probably don't need to build it yourself. Anyway, hope this helps!
