### ISSUE TITLE
height and width filter

### ISSUE THREAD

**Issue by bielocko** [PactInteractive/image-downloader#63]
Hi, can you please give back filter with sliders for height and width? Or can I somehow install old version with that feature?
![viber_image_2021-04-26_12-09-11](https://user-images.githubusercontent.com/13737959/116066637-8d38b900-a688-11eb-9174-e9ec990e2c0e.jpg)

Extension is useless for me without that filter :-(

**Comment by vdsabev** [comment]
The advanced filters are still available when you click the `+` button:

![toggle-advanced-filters](https://user-images.githubusercontent.com/1333274/116066876-3683ad00-a691-11eb-82e5-8f7b2a49590f.gif)

Your feedback is still helpful! I've now made the advanced filters expanded by default in 30644ae988aa41aabb1ff46e72408cebdf45a5ef which will be published as 3.0.3 later this week.

Let me know if you're having any other issues.

**Comment by bielocko** [comment]
thank you.
