### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Maddos75** [PactInteractive/image-downloader#65]
Impossible to see the images of instagram, it is possible that it does it also on other site 
https://i.imgur.com/EOnW1WM.png
![image](https://user-images.githubusercontent.com/83225663/116090800-89b32b00-a6a4-11eb-8877-54f44d0a5bbb.png)

**Comment by vdsabev** [comment]
Thanks for reporting this issue! I'll work on a fix this week and get back to you then.

**Comment by vdsabev** [comment]
Fixed in #66 and will be released in version 3.0.5 of the extension
