### ISSUE TITLE
Save to subfolder field no longer permits forward slash

### ISSUE THREAD

**Issue by mikvance** [PactInteractive/image-downloader#67]
Will this handy feature be returned to the extension? It saved a ton of time to be able to use the forward slash to send saved images to deeper subfolders.
![image](https://user-images.githubusercontent.com/19372422/116163547-f4c12980-a6c5-11eb-976f-bcea310d40a5.png)

**Comment by syd-h** [comment]
Not having access to additional sub folders totally breaks the usefulness of this for me too.

**Comment by vdsabev** [comment]
Oops 😅 I didn't know about this use case! So when some people suggested to disallow special characters I didn't think of preserving slashes.

Slashes are again allowed as of f27bf0aab5704a98fbdaaeb433f7d40f7b16ee17 and are available in version 3.0.6 of the extension. Please let me know how it works out for you!
