### ISSUE TITLE
Publish your extension to Microsoft Edge Addons website

### ISSUE THREAD

**Issue by nagachaitanyalokam** [PactInteractive/image-downloader#70]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by vdsabev** [comment]
Thanks @nagachaitanyalokam the extension is already pending review in the Microsoft Partner Center 😉
Something that would be helpful is if the review process went faster - while waiting for the Microsoft team to approve the extension, I've already published 5 new releases to the Google Chrome version.

**Comment by nagachaitanyalokam** [comment]
@vdsabev Thanks for your prompt response.

**Comment by nagachaitanyalokam** [comment]
Could you please write to Edge Support Team at the email address provided in the link [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team)? The review process in general should not take more than 7 business days.

**Comment by vdsabev** [comment]
Thanks for letting me know. It hasn't been 7 days yet but it would be better if we released the newer version 3.0.6 instead since it contains critical bug fixes. I have sent a message via the link you posted. Thanks again!

**Comment by nagachaitanyalokam** [comment]
Hello @vdsabev 

Did you get any update from the team?

**Comment by vdsabev** [comment]
The extension has now been published to the Microsoft Edge Add-on Store. Thanks for following up!
