### ISSUE TITLE
Folders are getting stuck

### ISSUE THREAD

**Issue by syd-h** [PactInteractive/image-downloader#73]
V3.2.2

The folders/sub folders are getting stuck to a single download location. Even if all folder text is removed it still sticks to a previous folder and not the main Chrome default download location.

Also in this version to get around the issue I've resorted to reloading the extension. I've noticed there are now 2 instances of the extension running. Maybe this has something todo with the issue?

**Comment by vdsabev** [comment]
Thanks for opening an issue! Couple of questions.

> The folders/sub folders are getting stuck to a single download location. Even if all folder text is removed it still sticks to a previous folder and not the main Chrome default download location.

Can you post the URL of the page where you're seeing this issue?

> Also in this version to get around the issue I've resorted to reloading the extension. I've noticed there are now 2 instances of the extension running. Maybe this has something todo with the issue?

How exactly are you reloading the extension? And how do you determine there are 2 instances running?

**Comment by syd-h** [comment]
I was downloading albums that were hosted on the Reddit with it's own image domain. Just recent housing albums from the FFXIV game. https://old.reddit.com/r/ffxivhomeandgarden/

As for reloading I was simply just using the built in Chrome Task Manager from right clicking on the top tab bar. Usually I can end process and just click the chrome pop up to reload but with it having 2 processes currently I would have to go to the extension management tab and click the reload button there instead.

Also interesting enough I had 2 instances running by upon grabbing screenshots only 1 returned after the reload. Though during such it still placed images into previous album folders. Though only did this 3 reload times compared to many more from earlier.

![image](https://user-images.githubusercontent.com/25559485/117217265-18bff180-adcf-11eb-8b61-acfda55a89ae.png)
![image](https://user-images.githubusercontent.com/25559485/117218170-a4864d80-add0-11eb-8f95-8685254feaa3.png)
![image](https://user-images.githubusercontent.com/25559485/117217410-5755ac00-adcf-11eb-83e6-87813734985d.png)

**Comment by vdsabev** [comment]
Thank you for the detailed explanation! With my previous fix I made the mistake of only testing the subfolders together with the file rename option - and it worked well. I'm assuming you weren't use the file rename option and that's why the folder was getting stuck?

I just published version 3.2.3 with [this fix](3b70627954850ff76f6b7946403baff7741bebd8) - it should be up in about an hour, pending a review by Google. Let me know how it works out once you get it!

As to the issue of having multiple processes, I'm not sure why that would be. Perhaps while updating to the new version the browser didn't terminate the previous background script? Have you tried restarting your browser, or your computer?

**Comment by syd-h** [comment]
Yea, I was not using the file rename. It's a nice addon but not for me. 

As for double process I am not exactly sure. I'm pretty sure I had restarted browser/pc in between my first encounter with the issue and coming back when I made the post a bit later when encountering it again feeling it was a bug.

I'll pop back in after it updates.

**Comment by syd-h** [comment]
So far so good in v3.2.3! Everything appears to be running as intended. 

Funny enough with that bug in v3.2.2 it seemed to also bug out the default download location for another extension. That one hovers images on mouse over then a hotkey can download to the default location. Had noticed a time or two yesterday before v3.2.3 pushed out.

Thanks for the quick fix still. :)

**Comment by vdsabev** [comment]
What you say about it bugging another extension's download location makes sense too. The way extensions interact can get complicated. Glad to hear it worked out in the end!
