### ISSUE TITLE
Recurrence

### ISSUE THREAD

**Issue by hageged** [PactInteractive/image-downloader#8]
Hi,
thanks for your extension.
I would much appreciate to set a timer that automatically comes back to a specific website and downloads all images. 
For instance unsplash.com offers new pictures every 10 days. If I could set it and forgetting it that'd be great.

**Comment by vdsabev** [comment]
While this idea sounds really useful, it seems to be data mining automation which is way beyond the scope of this extension. Perhaps someone else would be interested in working on a project like that.
